[workspace]
members = [
    "client_frontend",
    "fake_robot",
    "robot_data",
    "server",
]
resolver = "3"

[profile.dev]
lto = true
codegen-units = 8
panic = "abort"

[profile.wasm-release]
opt-level = "z"
lto = true
codegen-units = 8
panic = "abort"
inherits = "release"
